---
language: python
python: "2.7"

addons:
  chrome: stable

before_script:
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"
  - apt-get install -y chromium-browser

script:
  - google-chrome-stable --version
  - chromium-browser --version
